### ISSUE TITLE
Items in offhand contribute to money, but aren't sold(quick sell)

### ISSUE THREAD

**Issue by BillyDaPoop** [7sat/SSDynamicShop#17]
Items in offhand contribute to money, but aren't sold when using quick sell. This means that people can sell items without the items being taken away, and are able to very easily earn tons of money with no effort.

**Comment by kolya5544** [comment]
Doesn't replicate on DynamicShop 2.10.6

**Comment by kolya5544** [comment]
Works in DynamicShop 2.10.6

**Comment by jmanpenilla** [comment]
PR #29 Should fix this. Test it with [this jar](https://cdn.discordapp.com/attachments/592210263135223825/722191060352106638/DynamicShop-2.11.5-SNAPSHOT.jar)
