### ISSUE TITLE
Incorrect currency

### ISSUE THREAD

**Issue by Zhythero** [7sat/SSDynamicShop#2]
**Reproduce:**

1. Install GemsEconomy and SSDynamicShop
2. Set currency in GemsEconomy
3. Buy something you can't afford
4. ...
5. Profit! (Incorrect currency displayed)

**Versions:**
Gemsconomy: `4.8.3`
SSDynamicShop: `2.10.5`

**Comment by Tarlak333** [comment]
This issue appears to be related to issue #46.  This is a very serious economy breaking problem.
