### ISSUE TITLE
API is very limited

### ISSUE THREAD

**Issue by Nubebuster** [7sat/SSDynamicShop#21]
Could you add API for getting stocks and prices. I want to log those and display them in graphs on my website.

Stuff such as 
`
List<ItemStack> shopItems = DynaShopAPI.getItems();
int price = DynaShopAPI.getPrice(ItemStack item);
int stock = DynaShopAPI.getStock(ItemStack item);
int median= DynaShopAPI.getMedian(ItemStack item);`
etc.

Thanks in advance!

**Comment by jmanpenilla** [comment]
@Nubebuster I added some functions like you requested [here](https://github.com/jmanpenilla/SSDynamicShop/commit/1e135df8644cc15184e0e6185bfee6f7b737e20c#diff-cac9fc02cca667e3632732b20f41b61bR90)

[jar file](https://anonymousfiles.io/JFCJohlz/)

Let me know if this is what you wanted.
