### ISSUE TITLE
Armour is not sellable

### ISSUE THREAD

**Issue by Shewolf1896** [7sat/SSDynamicShop#3]
Put armour in the shop, for a price, plus a sell price.

A player buys the armour, decides to sell it, no durability taken off, can not sell it, does not read the armour as being the same item?

**Comment by kolya5544** [comment]
Same for shulker boxes

**Comment by jmanpenilla** [comment]
I can't reproduce this issue. Does it persist in the latest version?

**Comment by Tarlak333** [comment]
Issue never observed over past year of using this plugin.  reco closure
