### ISSUE TITLE
Unable to open shop GUI or use plugin

### ISSUE THREAD

**Issue by Kwikxilver** [7sat/SSDynamicShop#35]
When I do /shop, an internal error occurs and I'm unable to perform the command. No GUI pops up. Plugin seems to be unusable. Is there something I'm missing here?

Pastebin link to my latest.log, showing the error : [https://pastebin.com/sDwBegTg](https://pastebin.com/sDwBegTg)

Let me know if you need anything else to troubleshoot this, cheers.

**Comment by jmanpenilla** [comment]
I can't reproduce this. I'm guessing there is something wrong with your config files. Please share them in a gist/paste

**Comment by jmanpenilla** [comment]
@Kwikxilver @CACGaming Are you guys running the plugin for the first time or updating? Please let me know so I can resolve this bug

**Comment by jmanpenilla** [comment]
@CACGaming 's report:
I have the same issue:
https://pastebin.com/iku26CxN
This is the first install of the plugin and it fails when trying to open a shop.
Config.yml(Default): https://pastebin.com/tfwShV7c
Shop.yml(Default): https://pastebin.com/CquG6mgk

**Comment by CACGaming** [comment]
I have the same issue:
https://pastebin.com/iku26CxN
This is the first install of the plugin and it fails when trying to open a shop.
Config.yml(Default): https://pastebin.com/tfwShV7c
Shop.yml(Default): https://pastebin.com/CquG6mgk

**Comment by jmanpenilla** [comment]
@CACGaming Does the issue persist after a server restart?

**Comment by CACGaming** [comment]
@jmanpenilla It persists after restart and deleting the configuration to let it generate a new set

**Comment by jmanpenilla** [comment]
[configs.zip](https://github.com/7sat/SSDynamicShop/files/4886928/configs.zip)
If you try using my config here do you still get the error? (You can ignore the DynamicShop-Graph folder, it is for another plugin)

**Comment by CACGaming** [comment]
@jmanpenilla It works just fine with your configs

**Comment by Kwikxilver** [comment]
@jmanpenilla this was my first install of the plugin using the default configs.

After replacing my config folder with the one you installed, everything seems to work fine.

Maybe it's an error with the plugin file you uploaded to spigot?

**Comment by jmanpenilla** [comment]
I don't own the spigot page, 7sat does. He uploaded a build that wasn't ready yet (2.11.8-SNAPSHOT). Would you mind testing if the same issue happens or not with 2.11.7 when starting the plugin with no configs (ie for testing delete the configs and test with fresh 2.11.7 from spigot)? Knowing if the issue is still present/is not present in 2.11.7 will help me determine when the issue was introduced and help me to fix it.

**Comment by CACGaming** [comment]
@jmanpenilla It works fine with default configs on version 2.11.7, however upon opening the shop for the first time it is delayed and warns:
[21:38:19 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

It isnt another plugin causing that, it only happens after running /shop

**Comment by jmanpenilla** [comment]
Ok, I can reproduce it. Seems like the 2.11.8-SNAPSHOT build is broken. Use 2.11.7, or the 2.11.8 that 7sat will hopefully release soon based on his master branch.

**Comment by Tarlak333** [comment]
"[21:38:19 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!"

This warning (should) have nothing to do with SS Dynamic Shop, this comes from spigot/paper on startup.  This warning is not harmful and will not cause sever issues.  It's just spigots way of telling you a plugin or plugins don't have an API version specified in the "plugin.jar" file.  For example all plugins should have the following line:

api-version: 1.15

If the api-version is missing or is anything less than 1.13 it will spit out the above warning message and force spigot into legacy material support mode which should not impact anything.

Best of luck,

Tarlak333

**Comment by jmanpenilla** [comment]
that warning does not matter which you would know if you read it. however I will fix it. #37

**Comment by jmanpenilla** [comment]
This issue should be closed. Thanks
