### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by sketrick** [7sat/SSDynamicShop#39]
Hi, I would love a feature where you can have a "Wand" to right click a chest and sell all of it's contents (that exists in d-s) to dynamic shop.
Or use the Quick sell feature to bind to an item in config, that could sell everything form a chest when you right or left click it.(Can be optional in config)

**Comment by shmkane** [comment]
Hey @sketrick. I'm not dev for this plugin, but  [SellStick](https://www.spigotmc.org/resources/sell-stick-sell-wand.38119/) currently allows you to sell items from a chest like you said, but does NOT hook into DynamicShop just yet. I've created an [issue](https://github.com/7sat/SSDynamicShop/issues/43) that would allow for this to happen.

**Comment by 7sat** [comment]
https://github.com/7sat/SSDynamicShop/commit/191252fdcfae01b3d334b52fcf8893fe8eb43275

Issues will be tracked here : https://github.com/7sat/SSDynamicShop/issues/43
