### ISSUE TITLE
Don't compatible with 1.13.2

### ISSUE THREAD

**Issue by dellise26** [7sat/SSDynamicShop#40]
Hello, first of all i'm really interested in the good developpement of the plugin, good idea with good features, but sadly my server is on 1.13.2 and based on my console, the usage of the oak_sign is hardcoded, but it didn't exist in 1.13.2 so it crash.
Is it possible to put the material in the config, or at least using generic material and checking the version, thx for all.

**Comment by 7sat** [comment]
https://github.com/7sat/SSDynamicShop/commit/458e66e7bb740c3efe1b86661904e38c3d0bb0af
