### ISSUE TITLE
Latest PaperMC

### ISSUE THREAD

**Issue by Roshanxy** [7sat/SSDynamicShop#45]
Hi, 

This plugin is broken in the latest paper version. You cannot use this plugin at all with the latest version as you can take items from the shop menu out like a normal chest.

**Comment by Tarlak333** [comment]
Cannot duplicate.

I am using the latest Paper version (updated weekly) and have never experienced this issue.

**Comment by Roshanxy** [comment]
> Cannot duplicate.
> 
> I am using the latest Paper version (updated weekly) and have never experienced this issue.

It was fixed in this update
https://github.com/PaperMC/Paper/issues/5222
