### ISSUE TITLE
Maven build failure VSCode

### ISSUE THREAD

**Issue by xerminator** [7sat/SSDynamicShop#47]
Hi I am trying to add database functionality into the plugin and wanted to compile/build the project using maven like you did.

But when I tried I am getting this error.

[ERROR] Failed to execute goal on project DynamicShop: Could not resolve dependencies for project me.sat7:DynamicShop:jar:2.11.8: Failed to collect dependencies at me.clip:placeholderapi:jar:2.9.2:

Could you help me out here, cause I think the git repo might be missing a settings.xml or smth else to not get this error on compiling your code.

**Comment by igumen1990** [comment]
I also tried, there were also many different errors

**Comment by 7sat** [comment]
pom.xml updated. should be fixed now.
