### ISSUE TITLE
change the colors of "⬆%" or help to rebuild the plugin

### ISSUE THREAD

**Issue by igumen1990** [7sat/SSDynamicShop#48]
it seems to me that it will be better if you change the colors of the percentage increase in price (decrease in price) "⬆%" . if the price is higher than the established one, then it is profitable to sell to the store (green interest), but not profitable to buy (red).
if the price of the product is lower than the established one, then it is profitable to buy (green) but not profitable to sell (red).
or help me compile the plugin (in which I will change it myself) (if so, I will send the errors that occur when trying to compile)

**Comment by ACluco1** [comment]
yep, i was wondering if i could change those colors as well, so it would be a great change!

**Comment by 7sat** [comment]
Now you can edit arrow.
You can also disable it if you want.
